export const DUMMY_DATA = {
  success: true,
  message: "🚀 Candidates profiled successfully!",
  total_weight: 100,
  weight_status: "valid",
  candidates: [
    {
      recent_pubs: "8",
      works_count: "189",
      h_index: 37,
      employment: [
        {
          title: "director of informatics",
          organization: "National Center for Advancing Translational Sciences",
          start_date: "2020-02",
          end_date: "N/A",
        },
        {
          title: "assistant professor",
          organization: "Ohio State University",
          start_date: "2015-09",
          end_date: "2020-01",
        },
      ],
      is_founder: "False",
      universities: [
        "National Center for Advancing Translational Sciences",
        "National Institutes of Health",
        "The Ohio State University",
        "Center for Cancer Research",
        "The Ohio State University Comprehensive Cancer Center – Arthur G. James Cancer Hospital and Richard J. Solove Research Institute",
        "The Ohio State University Wexner Medical Center",
        "Ohio University",
        "National Institute of Arthritis and Musculoskeletal and Skin Diseases",
        "National Cancer Institute",
        "Pennsylvania State University",
      ],
      citations: 7364,
      roles: ["director of informatics", "assistant professor"],
      current_organization:
        "National Center for Advancing Translational Sciences",
      i10_index: "56",
      experience_years: 10,
      name: "Ewy A. Mathé",
      region: "MD",
      country: "US",
      current_position: "director of informatics",
      founder_roles: [],
      estimated_salary: "385000",
      skills: [
        "rna",
        "protein",
        "molecular",
        "bioinformatics",
        "R",
        "AI",
        "bioconductor",
      ],
      top_journal_pubs: "15",
      orcid_id: "0000-0003-4491-8107",
      career_progression_score: 0.0425,
      field: "Bioinformatics",
      education: [
        {
          degree: "PhD",
          institution: "George Mason University",
          start_date: "2001",
          end_date: "2006",
        },
      ],
      has_doctorate: "True",
      patent_count: "3",
      city: "Rockville",
      emerging_trend_alignment_score: 0.046,
      last_updated_utc: "2025-07-21T00:55:14.441413",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.3385,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Analyst Summary for Ewy A. Mathé:  Dr. Ewy A. Mathé is a distinguished informatics director at the National Center for Advancing Translational Sciences with a robust academic background spanning multiple prestigious institutions, including the National Institutes of Health and The Ohio State University. With a doctoral degree and over a decade of research experience, Dr. Mathé has established a significant academic footprint, evidenced by an impressive citation count of 7,364 and a notable h-index of 37.  Specializing in translational research informatics, Dr. Mathé demonstrates expertise across complex biomedical domains, particularly in cancer research and musculoskeletal science. While the current data suggests no direct industry collaborations or patent developments, the extensive academic network and affiliations with leading research centers indicate substantial scientific influence.  The candidate's KPI score of 0.3385 reflects a moderate research impact, with potential for further strategic development in translational science innovations. Dr. Mathé's professional trajectory suggests a strong commitment to advancing scientific knowledge through sophisticated informatics approaches, positioning her as a valuable contributor in the biomedical research ecosystem.",
    },






    // END
    {
      recent_pubs: "12",
      works_count: "65",
      h_index: 21,
      employment: [
        {
          title: "director",
          organization: "Salk Institute for Biological Studies",
          start_date: "2024-11-18",
          end_date: "N/A",
        },
        {
          title: "director",
          organization: "University of Illinois at Urbana-Champaign",
          start_date: "2022-09-06",
          end_date: "2024-10-11",
        },
        {
          title: "associate professor",
          organization: "California Polytechnic State University",
          start_date: "2016-09-06",
          end_date: "2022-09-05",
        },
        {
          title: "postdoctoral researcher",
          organization: "University of California Davis",
          start_date: "2012-12",
          end_date: "2016-09-02",
        },
      ],
      is_founder: "False",
      universities: [
        "California Polytechnic State University",
        "University of Illinois Urbana-Champaign",
        "Salk Institute for Biological Studies",
        "University of California, Davis",
        "Western Human Nutrition Research Center",
        "Agricultural Research Service",
        "United States Department of Agriculture",
        "West Health",
        "Jean Mayer Human Nutrition Research Center on Aging",
      ],
      citations: 2226,
      roles: [
        "director",
        "director",
        "associate professor",
        "postdoctoral researcher",
      ],
      current_organization: "Salk Institute for Biological Studies",
      i10_index: "34",
      experience_years: 13,
      name: "Michael R. La Frano",
      region: "Unknown",
      country: "US",
      current_position: "director",
      founder_roles: [],
      estimated_salary: "550000",
      skills: ["rna", "protein", "molecular", "R", "AI"],
      top_journal_pubs: "45",
      orcid_id: "0000-0002-2269-1688",
      career_progression_score: 0.0425,
      field: "Biotechnology",
      education: [
        {
          degree: "Ph.D.",
          institution: "University of California Davis",
          start_date: "2007-09-25",
          end_date: "2012-11-26",
        },
      ],
      has_doctorate: "True",
      patent_count: "8",
      city: "La Jolla",
      emerging_trend_alignment_score: 0.039,
      last_updated_utc: "2025-07-20T20:16:34.548184",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.3315,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Michael R. La Frano is a distinguished director at the Salk Institute for Biological Studies, demonstrating a robust academic trajectory across multiple prestigious research institutions. With 13 years of professional experience, he has established a significant scholarly footprint, evidenced by 2,226 citations and an h-Index of 21, indicating substantial academic impact in his field.  Dr. La Frano's academic credentials span multiple top-tier institutions, including the University of California, Davis and the University of Illinois Urbana-Champaign, showcasing a diverse and interdisciplinary research background. His professional affiliations with prominent research centers like the Western Human Nutrition Research Center and Jean Mayer Human Nutrition Research Center on Aging underscore his expertise in nutritional science and biomedical research.  While his publication record appears limited in this dataset, his citations suggest meaningful research contributions. His KPI score of 0.3315 reflects a moderate level of academic and research performance. Currently positioned as a director at the Salk Institute, Dr. La Frano likely plays a strategic role in advancing scientific research and institutional objectives.  Despite the absence of reported industry ties or patent innovations, his extensive institutional network and academic credentials position him as a credible research professional in the biomedical domain.",
    },
    {
      recent_pubs: "12",
      works_count: "282",
      h_index: 47,
      employment: [
        {
          title: "vice chair and associate professor",
          organization: "Cedars-Sinai Medical Center",
          start_date: "2022-12-31",
          end_date: "N/A",
        },
        {
          title: "associate professor",
          organization: "Columbia University",
          start_date: "2012-09-15",
          end_date: "2022-12-31",
        },
      ],
      is_founder: "False",
      universities: [
        "Columbia University",
        "Cedars-Sinai Medical Center",
        "Columbia University Irving Medical Center",
        "Stanford Health Care",
        "Herbert Irving Comprehensive Cancer Center",
        "New York Hospital Queens",
        "NewYork–Presbyterian Hospital",
        "National Institutes of Health",
        "National Institute of Nursing Research",
        "Institute of Bioinformatics",
      ],
      citations: 10422,
      roles: ["vice chair and associate professor", "associate professor"],
      current_organization: "Cedars-Sinai Medical Center",
      i10_index: "110",
      experience_years: 13,
      name: "Nicholas P. Tatonetti",
      region: "Unknown",
      country: "US",
      current_position: "vice chair and associate professor",
      founder_roles: [],
      estimated_salary: "588000",
      skills: [
        "rna",
        "protein",
        "molecular",
        "bioinformatics",
        "python",
        "R",
        "AI",
        "Machine learning",
        "drug discovery",
      ],
      top_journal_pubs: "45",
      orcid_id: "0000-0002-2700-2597",
      career_progression_score: 0.0425,
      field: "Bioinformatics",
      education: [
        {
          degree: "PhD",
          institution: "Stanford University",
          start_date: "2008-09-01",
          end_date: "2012-06-01",
        },
      ],
      has_doctorate: "True",
      patent_count: "8",
      city: "Los Angeles",
      emerging_trend_alignment_score: 0.039,
      last_updated_utc: "2025-07-21T00:21:00.579613",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.3315,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Candidate Summary:  Dr. Nicholas P. Tatonetti is a distinguished computational bioinformatics researcher with a robust academic profile, currently serving as Vice Chair and Associate Professor at Cedars-Sinai Medical Center. With 13 years of extensive research experience, he has established a significant scholarly reputation, evidenced by an impressive 10,422 citations and a highly regarded h-Index of 47.  Affiliated with prestigious institutions including Columbia University, Stanford Health Care, and the Herbert Irving Comprehensive Cancer Center, Dr. Tatonetti has demonstrated exceptional expertise in biomedical research and computational methodologies. His academic trajectory spans multiple renowned research environments, suggesting a comprehensive and interdisciplinary approach to scientific investigation.  While the candidate's publication count appears limited in the provided data, his substantial citation metrics indicate influential and impactful research contributions. The KPI score of 0.3315 reflects a moderate level of academic and research performance.  Dr. Tatonetti's professional profile suggests a strong commitment to advancing biomedical knowledge through sophisticated computational approaches, with potential specializations in bioinformatics, data science, and healthcare analytics. His diverse institutional affiliations underscore a collaborative and dynamic research orientation.",
    },
    {
      recent_pubs: "12",
      works_count: "137",
      h_index: 29,
      employment: [
        {
          title: "associate professor",
          organization: "Stanford University",
          start_date: "2012-08-01",
          end_date: "N/A",
        },
      ],
      is_founder: "False",
      universities: [
        "Stanford University",
        "Stanford Medicine",
        "Chan Zuckerberg Initiative (United States)",
        "Becton Dickinson (United States)",
        "Palo Alto University",
        "Howard Hughes Medical Institute",
        "University of California, Berkeley",
        "University of California, Los Angeles",
        "Technion – Israel Institute of Technology",
        "Los Alamos National Laboratory",
      ],
      citations: 6950,
      roles: ["associate professor"],
      current_organization: "Stanford University",
      i10_index: "45",
      experience_years: 13,
      name: "Adam de la Zerda",
      region: "CA",
      country: "US",
      current_position: "associate professor",
      founder_roles: [],
      estimated_salary: "367500",
      skills: [],
      top_journal_pubs: "45",
      orcid_id: "0000-0002-5617-0194",
      career_progression_score: 0.0425,
      field: "Biotechnology",
      education: [
        {
          degree: "Postdoctoral Fellowship",
          institution: "University of California Berkeley",
          start_date: "2011-02-01",
          end_date: "2012-07-01",
        },
        {
          degree: "PhD",
          institution: "Stanford University",
          start_date: "2007-09-01",
          end_date: "2011-06-01",
        },
        {
          degree: "MSc",
          institution: "Stanford University",
          start_date: "2005-09-01",
          end_date: "2007-06-01",
        },
        {
          degree: "BSc",
          institution: "Technion – Israel Institute of Technology ",
          start_date: "2002-09-01",
          end_date: "2005-06-01",
        },
      ],
      has_doctorate: "True",
      patent_count: "8",
      city: "Stanford",
      emerging_trend_alignment_score: 0.039,
      last_updated_utc: "2025-07-20T18:56:57.273123",
      has_masters: "True",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.3315,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Adam de la Zerda is a distinguished associate professor at Stanford University with a robust academic background spanning biomedical engineering and computational sciences. With 13 years of professional experience, he has established a significant research footprint, evidenced by an impressive 6,950 citations and an h-Index of 29.   Dr. de la Zerda has cultivated an interdisciplinary academic profile, demonstrating extensive collaboration across prestigious institutions including Stanford Medicine, Chan Zuckerberg Initiative, and multiple University of California campuses. His academic credentials are reinforced by doctoral and master's degrees, positioning him as a highly qualified researcher in emerging technological domains.  While the publication count appears limited in the provided data, his substantial citation metrics suggest impactful scholarly contributions. His professional network spans academic and research institutions across the United States, including Howard Hughes Medical Institute and Los Alamos National Laboratory.  With a relatively moderate KPI score of 0.3315, Dr. de la Zerda represents a promising researcher with potential for further academic and industry engagement. His cross-institutional experience and citation impact indicate a strong foundation in advanced research methodologies and interdisciplinary collaboration.",
    },
    {
      recent_pubs: "12",
      works_count: "168",
      h_index: 35,
      employment: [
        {
          title: "associate professor",
          organization: "Stanford University",
          start_date: "2020-09-01",
          end_date: "N/A",
        },
        {
          title: "assistant professor",
          organization: "Stanford University School of Medicine",
          start_date: "2016-09-01",
          end_date: "2020-08-31",
        },
      ],
      is_founder: "False",
      universities: [
        "Stanford University",
        "Stanford Medicine",
        "Columbia University",
        "University of Southern California",
        "Stratford University",
        "ORCID",
        "Palo Alto University",
        "Baxter (United States)",
        "Washington University in St. Louis",
        "Harvard University Press",
      ],
      citations: 6333,
      roles: ["associate professor", "assistant professor"],
      current_organization: "Stanford University",
      i10_index: "77",
      experience_years: 9,
      name: "Brice Gaudillière",
      region: "California",
      country: "US",
      current_position: "associate professor",
      founder_roles: [],
      estimated_salary: "367500",
      skills: ["rna", "R"],
      top_journal_pubs: "45",
      orcid_id: "0000-0002-3475-5706",
      career_progression_score: 0.0425,
      field: "Bioinformatics",
      education: [
        {
          degree: "MD",
          institution: "Harvard Medical School",
          start_date: "N/A",
          end_date: "N/A",
        },
        {
          degree: "PhD",
          institution: "Harvard University",
          start_date: "N/A",
          end_date: "N/A",
        },
      ],
      has_doctorate: "True",
      patent_count: "3",
      city: "Stanford",
      emerging_trend_alignment_score: 0.039,
      last_updated_utc: "2025-07-21T01:06:32.012319",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.3315,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Brice Gaudillière is an accomplished associate professor at Stanford University with a distinguished academic background spanning multiple prestigious institutions. With nine years of professional experience, he has established a significant research footprint, evidenced by an impressive 6,333 citations and a robust h-Index of 35.  Specializing in advanced academic research, Dr. Gaudillière has demonstrated expertise across interdisciplinary domains, with notable academic affiliations including Stanford Medicine, Columbia University, and Harvard University Press. His scholarly contributions reflect a rigorous approach to academic investigation, though current publication records suggest ongoing research development.  While industry collaboration data appears limited, his academic profile suggests strong potential for translational research and intellectual contributions. The candidate's KPI score of 0.3315 indicates moderate research impact and emerging scholarly influence.  Dr. Gaudillière's academic trajectory highlights a commitment to scholarly excellence, with a doctoral-level qualification underpinning his professional credibility. His diverse institutional exposure and substantial citation metrics position him as a promising research professional with potential for continued academic and intellectual growth.  The summary presents an objective assessment of Dr. Gaudillière's professional research profile, emphasizing academic strengths and potential future contributions.",
    },
    {
      recent_pubs: "8",
      works_count: "112",
      h_index: 27,
      employment: [
        {
          title: "associate professor rfa",
          organization: "UT MD Anderson Cancer Center",
          start_date: "2021-09-01",
          end_date: "N/A",
        },
        {
          title: "assistant professor rfa",
          organization: "UT MD Anderson Cancer Center",
          start_date: "2013-09-01",
          end_date: "2021-08-31",
        },
        {
          title: "post-doctoral fellow",
          organization: "Washington University Physicians",
          start_date: "2007-02-01",
          end_date: "2007-08-01",
        },
      ],
      is_founder: "False",
      universities: [
        "The University of Texas MD Anderson Cancer Center",
        "Mallinckrodt (United States)",
        "Carestream (United States)",
        "Washington University in St. Louis",
        "Imaging Center",
        "Zero to Three",
        "University of Notre Dame",
        "Chinese Academy of Sciences",
        "Howard Hughes Medical Institute",
      ],
      citations: 5380,
      roles: [
        "associate professor rfa",
        "assistant professor rfa",
        "post-doctoral fellow",
      ],
      current_organization: "UT MD Anderson Cancer Center",
      i10_index: "47",
      experience_years: 12,
      name: "Seth T. Gammon",
      region: "TX",
      country: "US",
      current_position: "associate professor rfa",
      founder_roles: [],
      estimated_salary: "380000",
      skills: ["rna", "protein", "molecular", "R", "AI"],
      top_journal_pubs: "15",
      orcid_id: "0000-0001-8647-0975",
      career_progression_score: 0.0375,
      field: "Biotechnology",
      education: [
        {
          degree: "Doctor of Philosophy - Chemical Biology",
          institution: "Washington University Physicians",
          start_date: "2000-09-01",
          end_date: "2007-02-01",
        },
        {
          degree: "Bachelor of Science, Minor Chemistry",
          institution: "University of Illinois",
          start_date: "1997-08-01",
          end_date: "2000-04-01",
        },
      ],
      has_doctorate: "True",
      patent_count: "3",
      city: "Houston",
      emerging_trend_alignment_score: 0.0425,
      last_updated_utc: "2025-07-20T19:17:54.666632",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.33,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Seth T. Gammon is a distinguished associate professor at UT MD Anderson Cancer Center with a robust 12-year career in biomedical research. Demonstrating substantial academic credentials, he has established a significant scholarly impact evidenced by an impressive 5,380 citations and an h-Index of 27, signaling influential contributions to his field.  His academic trajectory spans prestigious institutions including Washington University in St. Louis, the University of Notre Dame, and the Chinese Academy of Sciences, indicating a diverse and internationally-recognized research background. Affiliations with Howard Hughes Medical Institute further underscore his research credibility.  While current publication records appear limited, Dr. Gammon's extensive institutional affiliations and citation metrics suggest meaningful scientific contributions. His professional profile reflects deep expertise in biomedical research, with potential specializations in imaging technologies and translational medicine.  The candidate's KPI score of 0.33, though moderate, reflects a research profile with demonstrated potential for continued academic and scientific development. His professional positioning at MD Anderson Cancer Center, a world-renowned institution in cancer research, indicates ongoing engagement with cutting-edge medical research.",
    },
    {
      recent_pubs: "8",
      works_count: "96",
      h_index: 25,
      employment: [
        {
          title: "associate professor of microbiomes",
          organization: "University of Maine",
          start_date: "2024-07-01",
          end_date: "N/A",
        },
        {
          title: "assistant professor of animal and veterinary sciences",
          organization: "The University of Maine",
          start_date: "2019-09-01",
          end_date: "2024-06-30",
        },
        {
          title: "research assistant professor",
          organization: "University of Oregon",
          start_date: "2017-06-05",
          end_date: "2019-08-01",
        },
        {
          title: "post-doctoral researcher",
          organization: "Montana State University Bozeman",
          start_date: "2016-05-01",
          end_date: "2017-06-04",
        },
        {
          title: "post doctoral researcher",
          organization: "Montana State University Bozeman",
          start_date: "2015-04-07",
          end_date: "2016-04-30",
        },
      ],
      is_founder: "False",
      universities: [
        "University of Maine",
        "Media Working Group",
        "National Cold Water Marine Aquaculture Center",
        "Research Institute for Aquaculture No1",
        "University of Ibadan",
        "Montana State University",
        "University of Oregon",
        "University of Vermont",
      ],
      citations: 3521,
      roles: [
        "associate professor of microbiomes",
        "assistant professor of animal and veterinary sciences",
        "research assistant professor",
        "post-doctoral researcher",
        "post doctoral researcher",
      ],
      current_organization: "University of Maine",
      i10_index: "35",
      experience_years: 10,
      name: "Suzanne L. Ishaq",
      region: "Maine",
      country: "US",
      current_position: "associate professor of microbiomes",
      founder_roles: [],
      estimated_salary: "275000",
      skills: ["rna", "R", "AI", "DNA sequencing"],
      top_journal_pubs: "15",
      orcid_id: "0000-0002-2615-8055",
      career_progression_score: 0.0375,
      field: "Bioinformatics",
      education: [
        {
          degree: "PhD Animal, Nutrition, and Food Sciences",
          institution: "University of Vermont",
          start_date: "2010-07",
          end_date: "2015-03",
        },
        {
          degree: "Bachelor's of Science",
          institution: "University of Vermont",
          start_date: "2003",
          end_date: "2007",
        },
      ],
      has_doctorate: "True",
      patent_count: "2",
      city: "Orono",
      emerging_trend_alignment_score: 0.0425,
      last_updated_utc: "2025-07-21T02:14:57.574762",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.33,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Suzanne L. Ishaq is an accomplished associate professor of microbiomes at the University of Maine, with a distinguished academic career spanning approximately 10 years. Her research profile demonstrates significant scholarly impact, evidenced by an impressive citation count of 3,521 and a robust h-Index of 25, indicating substantial influence in her field of microbiome research.  Dr. Ishaq has cultivated a diverse academic background, engaging with multiple research institutions including the National Cold Water Marine Aquaculture Center and collaborating across international research networks. Her academic trajectory reflects a comprehensive approach to microbiological studies, with involvement in various research groups and institutions across the United States and internationally.  While her current publication count appears limited, her citation metrics suggest substantial research contributions and academic recognition. Her professional profile indicates a strong commitment to advanced scientific research, particularly in microbiome dynamics.  The candidate's KPI score of 0.33 suggests potential for further academic and research development. Dr. Ishaq represents a mid-career researcher with demonstrable expertise in microbiome studies, positioned at the intersection of academic research and scientific exploration.",
    },
    {
      recent_pubs: "8",
      works_count: "576",
      h_index: 67,
      employment: [
        {
          title: "division director",
          organization: "American Society of Clinicl Oncology",
          start_date: "2017-07-17",
          end_date: "N/A",
        },
        {
          title: "professor of biostatistics",
          organization:
            "Medical University of South Carolina - College of Medicine",
          start_date: "2007-02-15",
          end_date: "2007-07-01",
        },
        {
          title: "assistant professor",
          organization: "Johns Hopkins School of Medicine",
          start_date: "2000-02-01",
          end_date: "2007-01-15",
        },
      ],
      is_founder: "False",
      universities: [
        "American Society of Clinical Oncology",
        "Medical University of South Carolina",
        "MUSC Hollings Cancer Center",
        "Sidney Kimmel Comprehensive Cancer Center",
        "Novartis (Switzerland)",
        "RTI International",
        "Pfizer (United Kingdom)",
        "Merck (United Kingdom)",
        "AstraZeneca (Brazil)",
        "Bayer (United States)",
      ],
      citations: 19104,
      roles: [
        "division director",
        "professor of biostatistics",
        "assistant professor",
      ],
      current_organization: "American Society of Clinicl Oncology",
      i10_index: "228",
      experience_years: 15,
      name: "Elizabeth Garrett‐Mayer",
      region: "Virginia",
      country: "US",
      current_position: "division director",
      founder_roles: [],
      estimated_salary: "440000",
      skills: ["rna", "protein", "molecular", "R", "AI", "pcr"],
      top_journal_pubs: "45",
      orcid_id: "0000-0003-4709-0333",
      career_progression_score: 0.0425,
      field: "Bioinformatics",
      education: [
        {
          degree: "PhD",
          institution:
            "Johns Hopkins University Bloomberg School of Public Health",
          start_date: "1994-09-01",
          end_date: "2000-02-01",
        },
      ],
      has_doctorate: "True",
      patent_count: "2",
      city: "Alexandria",
      emerging_trend_alignment_score: 0.0375,
      last_updated_utc: "2025-07-20T23:45:32.909581",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.33,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Elizabeth Garrett-Mayer is a distinguished research leader in clinical oncology with over 15 years of comprehensive experience spanning academic and industry domains. As a division director at the American Society of Clinical Oncology, she has established a significant research footprint, demonstrating exceptional scholarly impact evidenced by her impressive 19,104 citations and a distinguished h-Index of 67.  Her academic trajectory encompasses prestigious institutions including the Medical University of South Carolina and Sidney Kimmel Comprehensive Cancer Center, highlighting her robust scientific credentials. Dr. Garrett-Mayer has cultivated extensive international research collaborations, engaging with leading pharmaceutical organizations such as Novartis, Pfizer, Merck, AstraZeneca, and Bayer.  While her publication record appears limited, her substantial citation metrics suggest high-quality, influential research contributions in clinical oncology. Her doctoral-level training and leadership role indicate a sophisticated understanding of complex medical research landscapes.  With a professional KPI score of 0.33, Dr. Garrett-Mayer represents a seasoned research professional bridging academic excellence and industry innovation in oncological research. Her multidisciplinary background positions her as a valuable contributor to advancing clinical oncology knowledge and practice.",
    },
    {
      recent_pubs: "12",
      works_count: "181",
      h_index: 21,
      employment: [
        {
          title: "assistant professor",
          organization: "University of Texas MD Anderson Cancer Center",
          start_date: "2019-10",
          end_date: "N/A",
        },
        {
          title: "postdoctoral fellow",
          organization: "University of Texas MD Anderson Cancer Center",
          start_date: "2017-09",
          end_date: "2019-09",
        },
        {
          title: "postdoctoral fellow",
          organization: "University of Washington",
          start_date: "2016-09",
          end_date: "2017-08",
        },
      ],
      is_founder: "False",
      universities: [
        "The University of Texas MD Anderson Cancer Center",
        "Texas Tech University",
        "University of California, Riverside",
        "Moffitt Cancer Center",
        "Mayo Clinic",
        "WinnMed",
        "Heidelberg (Poland)",
        "University of Hohenheim",
        "Southern University of Science and Technology",
        "Northeast Normal University",
      ],
      citations: 1577,
      roles: [
        "assistant professor",
        "postdoctoral fellow",
        "postdoctoral fellow",
      ],
      current_organization: "University of Texas MD Anderson Cancer Center",
      i10_index: "35",
      experience_years: 9,
      name: "Ruitao Lin",
      region: "TX",
      country: "US",
      current_position: "assistant professor",
      founder_roles: [],
      estimated_salary: "275000",
      skills: ["rna", "R", "AI"],
      top_journal_pubs: "8",
      orcid_id: "0000-0003-2244-131X",
      career_progression_score: 0.0375,
      field: "Bioinformatics",
      education: [
        {
          degree: "Ph.D.",
          institution: "University of Hong Kong",
          start_date: "2012-09",
          end_date: "2016-08",
        },
      ],
      has_doctorate: "True",
      patent_count: "2",
      city: "Houston",
      emerging_trend_alignment_score: 0.0425,
      last_updated_utc: "2025-07-21T00:59:32.843207",
      has_masters: "False",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.33,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Ruitao Lin is an accomplished academic researcher in oncology, currently serving as an Assistant Professor at the University of Texas MD Anderson Cancer Center. With 9 years of professional experience and a robust academic background spanning prestigious institutions including Mayo Clinic and UC Riverside, Dr. Lin demonstrates significant expertise in cancer research.  His scholarly impact is evidenced by an impressive citation count of 1,577 and an h-index of 21, indicating substantial intellectual contributions to the scientific community. While the publication record appears limited in this dataset, his citation metrics suggest meaningful research influence.  Dr. Lin's academic trajectory reflects a strong commitment to advanced scientific research, having completed his doctoral training and maintained affiliations with multiple renowned research institutions. His current position at MD Anderson, a world-leading cancer research center, underscores his professional credibility.  The candidate's KPI score of 0.33 suggests moderate research performance, with potential for further academic and industry engagement. Despite current limitations in industry ties, Dr. Lin's institutional affiliations and citation metrics position him as a promising researcher in the oncological sciences.",
    },
    {
      recent_pubs: "12",
      works_count: "174",
      h_index: 30,
      employment: [
        {
          title: "assistant professor",
          organization: "The University of Texas MD Anderson Cancer Center",
          start_date: "2023-09-01",
          end_date: "N/A",
        },
        {
          title: "resident",
          organization: "Harvard Radiation Oncology Program",
          start_date: "2019-07-01",
          end_date: "2023-06-30",
        },
      ],
      is_founder: "False",
      universities: [
        "The University of Texas MD Anderson Cancer Center",
        "University of Utah",
        "Broad Institute",
        "Stanford University",
        "Massachusetts General Hospital",
        "Icahn School of Medicine at Mount Sinai",
        "University of California, San Francisco",
        "Eastern Virginia Medical School",
        "University of Chicago",
        "University of Illinois Chicago",
      ],
      citations: 3636,
      roles: ["assistant professor", "resident"],
      current_organization: "The University of Texas MD Anderson Cancer Center",
      i10_index: "42",
      experience_years: 6,
      name: "Ryan J. Park",
      region: "Texas",
      country: "US",
      current_position: "assistant professor",
      founder_roles: [],
      estimated_salary: "165000",
      skills: ["crispr", "rna", "molecular", "R"],
      top_journal_pubs: "8",
      orcid_id: "0000-0003-4725-2937",
      career_progression_score: 0.0375,
      field: "Biotechnology",
      education: [
        {
          degree: "MD",
          institution: "Harvard Medical School",
          start_date: "2012",
          end_date: "2018",
        },
        {
          degree: "B.S., M.S.",
          institution: "Yale University",
          start_date: "2008",
          end_date: "2012",
        },
      ],
      has_doctorate: "True",
      patent_count: "3",
      city: "Houston",
      emerging_trend_alignment_score: 0.0425,
      last_updated_utc: "2025-07-20T18:36:27.790943",
      has_masters: "True",
      scientific_technical_foundation_hits: 0,
      matched_edu_hits: 0,
      industry_hits: 0,
      firms_hits: 0,
      skills_hits: 0,
      kpi_score: 0.33,
      scientific_technical_foundationscore: 0.0,
      top_academic_institutionscore: 0.0,
      digital_computing_skillsscore: 0.0,
      industrial_collaborationscore: 0.0,
      global_firmsscore: 0.0,
      patent_countscore: 0.1,
      research_credentialsscore: 0.05,
      recent_pubsscore: 0.1,
      founder_flagscore: 0.0,
      summary:
        "Research Profile Summary:  Dr. Ryan J. Park is an accomplished academic researcher in biomedical sciences with a robust multi-institutional background spanning prestigious research centers. As an assistant professor at the University of Texas MD Anderson Cancer Center, Dr. Park demonstrates significant academic credentials across multiple leading institutions including Stanford University, Broad Institute, and the University of California, San Francisco.  With 6 years of research experience, Dr. Park has established a notable scholarly profile evidenced by 3,636 citations and an h-Index of 30, indicating substantial scientific impact and recognition in his field. His academic trajectory reflects strong interdisciplinary expertise and potential for advanced research contributions.  While current publication records show limited direct output, his citation metrics suggest significant underlying research influence. The comprehensive academic training across multiple renowned institutions positions Dr. Park as a promising researcher with potential for innovative scientific breakthroughs.  The candidate's KPI score of 0.33 reflects emerging potential, with considerable room for future academic and research development. His affiliation with MD Anderson Cancer Center, a world-leading cancer research institution, further underscores his professional trajectory and commitment to cutting-edge medical research.",
    },
  ],
  total_candidates: 10,
};
