const scores = [
  {
    orcid_id: "1",
    name: "John Doe",
    career_progression_score: 0.046,
    emerging_trend_alignment_score: 0.0,
    scientific_technical_foundationscore: 0.0,
    top_academic_institutionscore: 0.0,
    digital_computing_skillsscore: 0.0,
    industrial_collaborationscore: 0.0,
    global_firmsscore: 0.0,
    patent_countscore: 0.1,
    research_credentialsscore: 0.05,
    recent_pubsscore: 0.1,
    founder_flagscore: 0.0,
  },
  {
    orcid_id: "2",
    name: "John Doe 2",
    career_progression_score: 0.046,
    emerging_trend_alignment_score: 0.0,
    scientific_technical_foundationscore: 0.0,
    top_academic_institutionscore: 0.0,
    digital_computing_skillsscore: 0.0,
    industrial_collaborationscore: 0.0,
    global_firmsscore: 0.0,
    patent_countscore: 0.1,
    research_credentialsscore: 0.05,
    recent_pubsscore: 0.1,
    founder_flagscore: 0.0,
  },
  {
    orcid_id: "3",
    name: "John Doe 3",
    career_progression_score: 0.046,
    emerging_trend_alignment_score: 0.0,
    scientific_technical_foundationscore: 0.0,
    top_academic_institutionscore: 0.0,
    digital_computing_skillsscore: 0.0,
    industrial_collaborationscore: 0.0,
    global_firmsscore: 0.0,
    patent_countscore: 0.1,
    research_credentialsscore: 0.05,
    recent_pubsscore: 0.1,
    founder_flagscore: 0.0,
  },
];
