import {
  Chart as ChartJS,
  LineElement,
  CategoryScale,
  LinearScale,
  PointElement,
  Legend,
  Tooltip,
} from "chart.js";
import { Line } from "react-chartjs-2";

ChartJS.register(
  LineElement,
  CategoryScale,
  LinearScale,
  PointElement,
  Legend,
  Tooltip
);

// const scores = [
//   {
//     orcid_id: "1",
//     name: "John Doe",
//     career_progression_score: 0.046,
//     emerging_trend_alignment_score: 0.057,
//     scientific_technical_foundationscore: 0.12,
//     top_academic_institutionscore: 0.08,
//     digital_computing_skillsscore: 0.15,
//     industrial_collaborationscore: 0.07,
//     global_firmsscore: 0.06,
//     patent_countscore: 0.1,
//     research_credentialsscore: 0.05,
//     recent_pubsscore: 0.1,
//     founder_flagscore: 0.02,
//   },
//   {
//     orcid_id: "2",
//     name: "John Doe 2",
//     career_progression_score: 0.065,
//     emerging_trend_alignment_score: 0.04,
//     scientific_technical_foundationscore: 0.1,
//     top_academic_institutionscore: 0.05,
//     digital_computing_skillsscore: 0.18,
//     industrial_collaborationscore: 0.06,
//     global_firmsscore: 0.03,
//     patent_countscore: 0.08,
//     research_credentialsscore: 0.04,
//     recent_pubsscore: 0.09,
//     founder_flagscore: 0.01,
//   },
//   {
//     orcid_id: "3",
//     name: "John Doe 3",
//     career_progression_score: 0.055,
//     emerging_trend_alignment_score: 0.05,
//     scientific_technical_foundationscore: 0.11,
//     top_academic_institutionscore: 0.06,
//     digital_computing_skillsscore: 0.14,
//     industrial_collaborationscore: 0.05,
//     global_firmsscore: 0.02,
//     patent_countscore: 0.09,
//     research_credentialsscore: 0.06,
//     recent_pubsscore: 0.08,
//     founder_flagscore: 0.03,
//   },
// ];

const scores = [
  {
    orcid_id: "1",
    name: "John Doe 1",
    career_progression_score: 0.046,
    emerging_trend_alignment_score: 0.057,
    scientific_technical_foundationscore: 0.12,
    top_academic_institutionscore: 0.08,
    digital_computing_skillsscore: 0.15,
    industrial_collaborationscore: 0.07,
    global_firmsscore: 0.06,
    patent_countscore: 0.1,
    research_credentialsscore: 0.05,
    recent_pubsscore: 0.1,
    founder_flagscore: 0.02,
  },
  {
    orcid_id: "2",
    name: "John Doe 2",
    career_progression_score: 0.065,
    emerging_trend_alignment_score: 0.04,
    scientific_technical_foundationscore: 0.1,
    top_academic_institutionscore: 0.05,
    digital_computing_skillsscore: 0.18,
    industrial_collaborationscore: 0.06,
    global_firmsscore: 0.03,
    patent_countscore: 0.08,
    research_credentialsscore: 0.04,
    recent_pubsscore: 0.09,
    founder_flagscore: 0.01,
  },
  {
    orcid_id: "3",
    name: "John Doe 3",
    career_progression_score: 0.055,
    emerging_trend_alignment_score: 0.05,
    scientific_technical_foundationscore: 0.11,
    top_academic_institutionscore: 0.06,
    digital_computing_skillsscore: 0.14,
    industrial_collaborationscore: 0.05,
    global_firmsscore: 0.02,
    patent_countscore: 0.09,
    research_credentialsscore: 0.06,
    recent_pubsscore: 0.08,
    founder_flagscore: 0.03,
  },
  {
    orcid_id: "4",
    name: "John Doe 4",
    career_progression_score: 0.07,
    emerging_trend_alignment_score: 0.06,
    scientific_technical_foundationscore: 0.13,
    top_academic_institutionscore: 0.1,
    digital_computing_skillsscore: 0.17,
    industrial_collaborationscore: 0.08,
    global_firmsscore: 0.05,
    patent_countscore: 0.07,
    research_credentialsscore: 0.03,
    recent_pubsscore: 0.07,
    founder_flagscore: 0.01,
  },
  {
    orcid_id: "5",
    name: "John Doe 5",
    career_progression_score: 0.06,
    emerging_trend_alignment_score: 0.03,
    scientific_technical_foundationscore: 0.09,
    top_academic_institutionscore: 0.04,
    digital_computing_skillsscore: 0.16,
    industrial_collaborationscore: 0.07,
    global_firmsscore: 0.04,
    patent_countscore: 0.1,
    research_credentialsscore: 0.07,
    recent_pubsscore: 0.06,
    founder_flagscore: 0.02,
  },
  {
    orcid_id: "6",
    name: "John Doe 6",
    career_progression_score: 0.05,
    emerging_trend_alignment_score: 0.045,
    scientific_technical_foundationscore: 0.1,
    top_academic_institutionscore: 0.09,
    digital_computing_skillsscore: 0.13,
    industrial_collaborationscore: 0.09,
    global_firmsscore: 0.06,
    patent_countscore: 0.06,
    research_credentialsscore: 0.05,
    recent_pubsscore: 0.1,
    founder_flagscore: 0.04,
  },
  {
    orcid_id: "7",
    name: "John Doe 7",
    career_progression_score: 0.08,
    emerging_trend_alignment_score: 0.07,
    scientific_technical_foundationscore: 0.14,
    top_academic_institutionscore: 0.12,
    digital_computing_skillsscore: 0.19,
    industrial_collaborationscore: 0.1,
    global_firmsscore: 0.08,
    patent_countscore: 0.05,
    research_credentialsscore: 0.06,
    recent_pubsscore: 0.09,
    founder_flagscore: 0.03,
  },
  {
    orcid_id: "8",
    name: "John Doe 8",
    career_progression_score: 0.045,
    emerging_trend_alignment_score: 0.05,
    scientific_technical_foundationscore: 0.1,
    top_academic_institutionscore: 0.06,
    digital_computing_skillsscore: 0.12,
    industrial_collaborationscore: 0.04,
    global_firmsscore: 0.03,
    patent_countscore: 0.09,
    research_credentialsscore: 0.04,
    recent_pubsscore: 0.07,
    founder_flagscore: 0.01,
  },
  {
    orcid_id: "9",
    name: "John Doe 9",
    career_progression_score: 0.066,
    emerging_trend_alignment_score: 0.042,
    scientific_technical_foundationscore: 0.08,
    top_academic_institutionscore: 0.03,
    digital_computing_skillsscore: 0.14,
    industrial_collaborationscore: 0.06,
    global_firmsscore: 0.05,
    patent_countscore: 0.07,
    research_credentialsscore: 0.06,
    recent_pubsscore: 0.08,
    founder_flagscore: 0.02,
  },
  {
    orcid_id: "10",
    name: "John Doe 10",
    career_progression_score: 0.07,
    emerging_trend_alignment_score: 0.06,
    scientific_technical_foundationscore: 0.13,
    top_academic_institutionscore: 0.1,
    digital_computing_skillsscore: 0.15,
    industrial_collaborationscore: 0.07,
    global_firmsscore: 0.06,
    patent_countscore: 0.08,
    research_credentialsscore: 0.05,
    recent_pubsscore: 0.09,
    founder_flagscore: 0.02,
  },
];


const metrics = [
  "career_progression_score",
  "emerging_trend_alignment_score",
  "scientific_technical_foundationscore",
  "top_academic_institutionscore",
  "digital_computing_skillsscore",
  "industrial_collaborationscore",
  "global_firmsscore",
  "patent_countscore",
  "research_credentialsscore",
  "recent_pubsscore",
  "founder_flagscore",
];

const chartData = {
  labels: metrics.map((metric) =>
    metric.replace(/_/g, " ").replace("score", "").trim()
  ),
  datasets: scores.map((person, idx) => ({
    label: person.name,
    data: metrics.map((key) => person[key]),
    borderColor: `hsl(${(idx * 100) % 360}, 70%, 50%)`,
    backgroundColor: `hsl(${(idx * 100) % 360}, 70%, 70%)`,
    tension: 0.3,
    fill: false,
  })),
};

const options = {
  responsive: true,
  plugins: {
    legend: {
      position: "top",
    },
    tooltip: {
      mode: "index",
      intersect: false,
    },
  },
  scales: {
    y: {
      beginAtZero: true,
      max: 0.2, // set max value according to your range
    },
  },
};

export default function LineChart() {
  return <Line data={chartData} options={options} />;
}
